### ISSUE TITLE
🐛　MakePDFGUI フォルダー指定できない

### ISSUE THREAD

**Issue by jhyong0130** [Okapi-dog/img-ocr-pdf#2]
## Description
- Output Directory を指定する際にsaveボタンが押せない

## Screenshot
<img width="828" alt="Screenshot 2024-12-23 at 10 42 20" src="https://github.com/user-attachments/assets/f118ef58-1e5c-4345-904e-a2d26e79b545" />

## Environment
- MacOS 15.0.1
- Python v3.10.12

**Comment by Okapi-dog** [comment]
img folderはディレクトリ指定だけど、pdf fileは名前をつけて保存って感じになってる。
変えた方がいいかな？

**Comment by jhyong0130** [comment]
@Okapi-dog 
なるほど！一応Set PDF fileのボタンを押すとフォルダ選択のwindowが勝手に開くのと、デフォルトで入力欄がパスになってて、そのままsaveを押すと.pdfじゃないのでエラーになってた。
名前を付けるだと、Set filenameとかにして、実装の方に
1. フォルダ選択が開かない
2. `.pdf`の拡張子は裏のコードでつける
にした方がいいかもね
